dist: trusty

language: generic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.21.0/bazel_0.21.0-linux-x86_64.deb
  - sha256sum -c tools/bazel_0.21.0-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.21.0-linux-x86_64.deb

script:
  - # Test the maven integration's internal unit tests
  - bazel test //...
  - # Exercise the sample project.
  - cd test/test_workspace
  - bazel test //...
