dist: xenial

language: generic

os:
  - linux
  - osx

env:
  global:
    - BAZEL_DOWNLOAD_PREFIX=https://github.com/bazelbuild/bazel/releases/download

  matrix:
    - SEGMENT="." BAZEL_VERSION="0.26.1"
    - SEGMENT="test/test_workspace" BAZEL_VERSION="0.26.1"
    - SEGMENT="." BAZEL_VERSION="0.27.0"
    - SEGMENT="test/test_workspace" BAZEL_VERSION="0.27.0"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - zip
      - g++
      - zlib1g-dev
      - unzip
      - python3
  homebrew:
    packages:
      - wget
    update: true

before_install:
  - source tools/.travis.${TRAVIS_OS_NAME}
  - wget ${BAZEL_DOWNLOAD_PREFIX}/${BAZEL_VERSION}/${BAZEL_INSTALLER}
  - ${SHA_CMD} -c tools/${BAZEL_INSTALLER}.sha256

install:
  - ${INSTALL} ${BAZEL_INSTALLER}
  - bazel version

script:
  - # Test each root in the build matrix.
  - cd ${HOME}/build/${TRAVIS_REPO_SLUG}/${SEGMENT}
  - bazel test //...
